### ISSUE TITLE
Suggestion: Replace turnCount with a boolean variable

### ISSUE THREAD

**Issue by MissStrong** [CaydenFerguson/Checkers#10]
Since turnCount only has the values 1 and 2, it can be replaced with a boolean. This would reduce the number of lines needed to indicate when the next phase of a turn has begun, since you can easily change the value of a boolean to its opposite by putting `b = !b`. 

One suggestion for the variable name is`isSelected`. Instead of `turnCount = 1`, you'd have `isSelected = false` and instead of `turnCount = 2`, you'd have `isSelected = true`.

**Comment by CaydenFerguson** [comment]
Fixed by Reg
