### ISSUE TITLE
Suggestion: Make multiple-jumping possible

### ISSUE THREAD

**Issue by MissStrong** [CaydenFerguson/Checkers#8]
You could make double, triple, and other n-tuple jumps possible by doing the following immediately after a single jump has occurred:
* check whether there is a jumpable piece diagonally above (for black and kings) and/or diagonally below (for red and kings) the current piece
* if there is a jumpable piece, allow the user to either jump it (by clicking on the cell it would go to), or end their turn (by clicking on their current cell)

**Comment by CaydenFerguson** [comment]
Added by Reg
